comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false  # Comment on every PR, even if coverage doesn’t change
  require_base: true
  require_head: true

coverage:
  status:
    project:
      default:
        target: 80%  # Fail if coverage is below 80%
        threshold: 1%  # Allow 1% drop without failing
    patch:
      default:
        target: 80%
        threshold: 0%
